name: Build & Push Frontend Docker Image

on:
  push:
    branches:
      - main  # main 브랜치에 Push할 때 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

      - name: Build Docker Image
        run: docker build -t kimdaewhi/my-app:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push kimdaewhi/my-app:latest
